### ISSUE TITLE
Asephena's Wrath journal entry

### ISSUE THREAD

**Issue by Issacar13** [ChasarooniZ/abomination-vaults-expanded#19]
Seems like the journal entry is not properly linked with the compendium,

<img width="962" height="800" alt="Image" src="https://github.com/user-attachments/assets/8485d5d3-4d48-48ad-abf7-22ea879f5fab" />

**Comment by Issacar13** [comment]
<img width="954" height="792" alt="Image" src="https://github.com/user-attachments/assets/c5bcb2dc-d0c1-46a8-857c-85468b144db4" />

**Comment by Issacar13** [comment]
I re-imported the compendium to see if it would resolve the problem, but it didn't

**Comment by ChasarooniZ** [comment]
Fixed in newest release

**Comment by xddViper** [comment]
Seems like the fix does not work, I still have the journal not linked properly. I created a new world with only Abomination Vaults and Abomination Vaults Expanded modules activated to be sure and it does not work there.

<img width="955" height="468" alt="Image" src="https://github.com/user-attachments/assets/4d13f694-3018-4064-a12a-70de9ffd6318" />
